### PR TITLE
Add additional information about zeppelin user credential

### PR DESCRIPTION
**Pull request by anthonycorbacho**
This bring information about how to set up his zeppelin with zeppelin and shiro.

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
@NFLabs/nflabs-memeber can you review this pr, i would like to deploy a fresh release of zeppelinhub to prod.

**Comment by AhyoungRyu** [comment]
@anthonycorbacho May I add this information to the new ZeppelinHub documentation page too ?  : )

**Comment by anthonycorbacho** [comment]
Sure

**Comment by khalidhuseynov** [comment]
@anthonycorbacho thanks for updating the docs. LGTM except those minors. Also the image has title of `Edit Instance` instead of adding new one, but it doesn't matter much I guess :)

**Pull request merged**
